<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="research\**\*.cs" />
    <None Update="overlay.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="generated-map-224593721.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="map-generation-data.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="room.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
